//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Enrichment__CallCredit_API_.DataAppendService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestDataRequest", Namespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0")]
    [System.SerializableAttribute()]
    public partial class TestDataRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestDataResponse", Namespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0")]
    [System.SerializableAttribute()]
    public partial class TestDataResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariablesRequest", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class DataVariablesRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientUrnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientBillingRefField;
        
        private string PurposeField;
        
        private string LicenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AddressLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.AddressElements AddressElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.NameElements NameElementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.KeyField[] KeyFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.RequestedField[] RequestedFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.Option[] OptionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientUrn {
            get {
                return this.ClientUrnField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientUrnField, value) != true)) {
                    this.ClientUrnField = value;
                    this.RaisePropertyChanged("ClientUrn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ClientBillingRef {
            get {
                return this.ClientBillingRefField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientBillingRefField, value) != true)) {
                    this.ClientBillingRefField = value;
                    this.RaisePropertyChanged("ClientBillingRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Licence {
            get {
                return this.LicenceField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenceField, value) != true)) {
                    this.LicenceField = value;
                    this.RaisePropertyChanged("Licence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string[] AddressLines {
            get {
                return this.AddressLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLinesField, value) != true)) {
                    this.AddressLinesField = value;
                    this.RaisePropertyChanged("AddressLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.AddressElements AddressElements {
            get {
                return this.AddressElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressElementsField, value) != true)) {
                    this.AddressElementsField = value;
                    this.RaisePropertyChanged("AddressElements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Fullname {
            get {
                return this.FullnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullnameField, value) != true)) {
                    this.FullnameField = value;
                    this.RaisePropertyChanged("Fullname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.NameElements NameElements {
            get {
                return this.NameElementsField;
            }
            set {
                if ((object.ReferenceEquals(this.NameElementsField, value) != true)) {
                    this.NameElementsField = value;
                    this.RaisePropertyChanged("NameElements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.KeyField[] KeyFields {
            get {
                return this.KeyFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyFieldsField, value) != true)) {
                    this.KeyFieldsField = value;
                    this.RaisePropertyChanged("KeyFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.RequestedField[] RequestedFields {
            get {
                return this.RequestedFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedFieldsField, value) != true)) {
                    this.RequestedFieldsField = value;
                    this.RaisePropertyChanged("RequestedFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Option[] Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressElements", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class AddressElements : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganisationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubBuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentThoroughfareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThoroughfareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DependentLocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Organisation {
            get {
                return this.OrganisationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationField, value) != true)) {
                    this.OrganisationField = value;
                    this.RaisePropertyChanged("Organisation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubBuildingName {
            get {
                return this.SubBuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubBuildingNameField, value) != true)) {
                    this.SubBuildingNameField = value;
                    this.RaisePropertyChanged("SubBuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNumberField, value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DependentThoroughfare {
            get {
                return this.DependentThoroughfareField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentThoroughfareField, value) != true)) {
                    this.DependentThoroughfareField = value;
                    this.RaisePropertyChanged("DependentThoroughfare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Thoroughfare {
            get {
                return this.ThoroughfareField;
            }
            set {
                if ((object.ReferenceEquals(this.ThoroughfareField, value) != true)) {
                    this.ThoroughfareField = value;
                    this.RaisePropertyChanged("Thoroughfare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string DependentLocality {
            get {
                return this.DependentLocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.DependentLocalityField, value) != true)) {
                    this.DependentLocalityField = value;
                    this.RaisePropertyChanged("DependentLocality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Locality {
            get {
                return this.LocalityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalityField, value) != true)) {
                    this.LocalityField = value;
                    this.RaisePropertyChanged("Locality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NameElements", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class NameElements : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Forename {
            get {
                return this.ForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForenameField, value) != true)) {
                    this.ForenameField = value;
                    this.RaisePropertyChanged("Forename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyField", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class KeyField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FieldField;
        
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestedField", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class RequestedField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Option", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class Option : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariablesResponse", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class DataVariablesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid RequestGuidField;
        
        private string StatusField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.Error ErrorField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.MatchLevel[] MatchLevelsField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.OutputField[] OutputFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestGuid {
            get {
                return this.RequestGuidField;
            }
            set {
                if ((this.RequestGuidField.Equals(value) != true)) {
                    this.RequestGuidField = value;
                    this.RaisePropertyChanged("RequestGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.MatchLevel[] MatchLevels {
            get {
                return this.MatchLevelsField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchLevelsField, value) != true)) {
                    this.MatchLevelsField = value;
                    this.RaisePropertyChanged("MatchLevels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.OutputField[] OutputFields {
            get {
                return this.OutputFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputFieldsField, value) != true)) {
                    this.OutputFieldsField = value;
                    this.RaisePropertyChanged("OutputFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.callcredit.co.uk/Common/Base/Error/1.0")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.ErrorDetail[] ErrorDetailsField;
        
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Data_Enrichment__CallCredit_API_.DataAppendService.ErrorDetail[] ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchLevel", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class MatchLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DatasetField;
        
        private string LevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Dataset {
            get {
                return this.DatasetField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetField, value) != true)) {
                    this.DatasetField = value;
                    this.RaisePropertyChanged("Dataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputField", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class OutputField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorDetail", Namespace="http://www.callcredit.co.uk/Common/Base/Error/1.0")]
    [System.SerializableAttribute()]
    public partial class ErrorDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatasetsRequest", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class DatasetsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowAllField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowAll {
            get {
                return this.ShowAllField;
            }
            set {
                if ((this.ShowAllField.Equals(value) != true)) {
                    this.ShowAllField = value;
                    this.RaisePropertyChanged("ShowAll");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatasetsResponse", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class DatasetsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid RequestGuidField;
        
        private string StatusField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.Dataset[] DatasetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestGuid {
            get {
                return this.RequestGuidField;
            }
            set {
                if ((this.RequestGuidField.Equals(value) != true)) {
                    this.RequestGuidField = value;
                    this.RaisePropertyChanged("RequestGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Dataset[] Datasets {
            get {
                return this.DatasetsField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetsField, value) != true)) {
                    this.DatasetsField = value;
                    this.RaisePropertyChanged("Datasets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dataset", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class Dataset : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldsRequest", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class FieldsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowAllField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatasetName {
            get {
                return this.DatasetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetNameField, value) != true)) {
                    this.DatasetNameField = value;
                    this.RaisePropertyChanged("DatasetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowAll {
            get {
                return this.ShowAllField;
            }
            set {
                if ((this.ShowAllField.Equals(value) != true)) {
                    this.ShowAllField = value;
                    this.RaisePropertyChanged("ShowAll");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldsResponse", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class FieldsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid RequestGuidField;
        
        private string StatusField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.Field[] FieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestGuid {
            get {
                return this.RequestGuidField;
            }
            set {
                if ((this.RequestGuidField.Equals(value) != true)) {
                    this.RequestGuidField = value;
                    this.RaisePropertyChanged("RequestGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Field[] Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Field", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class Field : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasLookupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnabledField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dataset {
            get {
                return this.DatasetField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetField, value) != true)) {
                    this.DatasetField = value;
                    this.RaisePropertyChanged("Dataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Level {
            get {
                return this.LevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LevelField, value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Length {
            get {
                return this.LengthField;
            }
            set {
                if ((this.LengthField.Equals(value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool HasLookups {
            get {
                return this.HasLookupsField;
            }
            set {
                if ((this.HasLookupsField.Equals(value) != true)) {
                    this.HasLookupsField = value;
                    this.RaisePropertyChanged("HasLookups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool Enabled {
            get {
                return this.EnabledField;
            }
            set {
                if ((this.EnabledField.Equals(value) != true)) {
                    this.EnabledField = value;
                    this.RaisePropertyChanged("Enabled");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupsRequest", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class LookupsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatasetName {
            get {
                return this.DatasetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetNameField, value) != true)) {
                    this.DatasetNameField = value;
                    this.RaisePropertyChanged("DatasetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupsResponse", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class LookupsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid RequestGuidField;
        
        private string StatusField;
        
        private Data_Enrichment__CallCredit_API_.DataAppendService.Error ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Data_Enrichment__CallCredit_API_.DataAppendService.Lookup[] LookupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid RequestGuid {
            get {
                return this.RequestGuidField;
            }
            set {
                if ((this.RequestGuidField.Equals(value) != true)) {
                    this.RequestGuidField = value;
                    this.RaisePropertyChanged("RequestGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Error Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.Lookup[] Lookups {
            get {
                return this.LookupsField;
            }
            set {
                if ((object.ReferenceEquals(this.LookupsField, value) != true)) {
                    this.LookupsField = value;
                    this.RaisePropertyChanged("Lookups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lookup", Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0")]
    [System.SerializableAttribute()]
    public partial class Lookup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatasetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dataset {
            get {
                return this.DatasetField;
            }
            set {
                if ((object.ReferenceEquals(this.DatasetField, value) != true)) {
                    this.DatasetField = value;
                    this.RaisePropertyChanged("Dataset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0", ConfigurationName="DataAppendService.IDataAppendService")]
    public interface IDataAppendService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0) of message TestRequest does not match the default value (http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0/IServiceModule/T" +
            "est", ReplyAction="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0/IServiceModule/T" +
            "estResponse")]
        Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse Test(Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0/IServiceModule/T" +
            "est", ReplyAction="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0/IServiceModule/T" +
            "estResponse")]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse> TestAsync(Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDataVariables", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDataVariablesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDataVariablesIOperationFaultDetailsFault", Name="anyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesResponse GetDataVariables(Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDataVariables", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDataVariablesResponse")]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesResponse> GetDataVariablesAsync(Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDatasets", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDatasetsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDatasetsIOperationFaultDetailsFault", Name="anyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsResponse GetDatasets(Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDatasets", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etDatasetsResponse")]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsResponse> GetDatasetsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etFields", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etFieldsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etFieldsIOperationFaultDetailsFault", Name="anyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        Data_Enrichment__CallCredit_API_.DataAppendService.FieldsResponse GetFields(Data_Enrichment__CallCredit_API_.DataAppendService.FieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etFields", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etFieldsResponse")]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.FieldsResponse> GetFieldsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.FieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etLookups", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etLookupsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etLookupsIOperationFaultDetailsFault", Name="anyType", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        Data_Enrichment__CallCredit_API_.DataAppendService.LookupsResponse GetLookups(Data_Enrichment__CallCredit_API_.DataAppendService.LookupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etLookups", ReplyAction="http://www.callcredit.co.uk/MsdWebApi/IDataAppendService/1.0/IDataAppendService/G" +
            "etLookupsResponse")]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.LookupsResponse> GetLookupsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.LookupsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0", IsWrapped=true)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0", Order=0)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.TestDataRequest request;
        
        public TestRequest() {
        }
        
        public TestRequest(Data_Enrichment__CallCredit_API_.DataAppendService.TestDataRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.callcredit.co.uk/Common/ServiceStarter/Interfaces/1.0", Order=0)]
        public Data_Enrichment__CallCredit_API_.DataAppendService.TestDataResponse TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(Data_Enrichment__CallCredit_API_.DataAppendService.TestDataResponse TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataAppendServiceChannel : Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataAppendServiceClient : System.ServiceModel.ClientBase<Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService>, Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService {
        
        public DataAppendServiceClient() {
        }
        
        public DataAppendServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataAppendServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAppendServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataAppendServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService.Test(Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public Data_Enrichment__CallCredit_API_.DataAppendService.TestDataResponse Test(Data_Enrichment__CallCredit_API_.DataAppendService.TestDataRequest request) {
            Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest inValue = new Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest();
            inValue.request = request;
            Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse retVal = ((Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService)(this)).Test(inValue);
            return retVal.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse> Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService.TestAsync(Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.TestResponse> TestAsync(Data_Enrichment__CallCredit_API_.DataAppendService.TestDataRequest request) {
            Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest inValue = new Data_Enrichment__CallCredit_API_.DataAppendService.TestRequest();
            inValue.request = request;
            return ((Data_Enrichment__CallCredit_API_.DataAppendService.IDataAppendService)(this)).TestAsync(inValue);
        }
        
        public Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesResponse GetDataVariables(Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesRequest request) {
            return base.Channel.GetDataVariables(request);
        }
        
        public System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesResponse> GetDataVariablesAsync(Data_Enrichment__CallCredit_API_.DataAppendService.DataVariablesRequest request) {
            return base.Channel.GetDataVariablesAsync(request);
        }
        
        public Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsResponse GetDatasets(Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsRequest request) {
            return base.Channel.GetDatasets(request);
        }
        
        public System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsResponse> GetDatasetsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.DatasetsRequest request) {
            return base.Channel.GetDatasetsAsync(request);
        }
        
        public Data_Enrichment__CallCredit_API_.DataAppendService.FieldsResponse GetFields(Data_Enrichment__CallCredit_API_.DataAppendService.FieldsRequest request) {
            return base.Channel.GetFields(request);
        }
        
        public System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.FieldsResponse> GetFieldsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.FieldsRequest request) {
            return base.Channel.GetFieldsAsync(request);
        }
        
        public Data_Enrichment__CallCredit_API_.DataAppendService.LookupsResponse GetLookups(Data_Enrichment__CallCredit_API_.DataAppendService.LookupsRequest request) {
            return base.Channel.GetLookups(request);
        }
        
        public System.Threading.Tasks.Task<Data_Enrichment__CallCredit_API_.DataAppendService.LookupsResponse> GetLookupsAsync(Data_Enrichment__CallCredit_API_.DataAppendService.LookupsRequest request) {
            return base.Channel.GetLookupsAsync(request);
        }
    }
}
